name: prometheus
namespace: prometheus
replicas: 1

image:
  repository: prom/prometheus
  tag: latest
  pullPolicy: Always

service:
  type: NodePort

ports:
  - 9090

volumes:
  - name: data
    hostPath: "/mnt/core_data/k3s/prometheus"
    mountPath: "/prometheus"

configMounts:
  - name: prometheus-config
    configMap: prometheus-config
    mountPath: /etc/prometheus/prometheus.yml
    subPath: prometheus.yml
    readOnly: true

configMaps:
  - name: prometheus
    path: config/prometheus.yml

ingress:
  hosts:
    - domain: prometheus.k3s.ravnet
      port: 9090
    - domain: prometheus.ravcube.com
      port: 9090