global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'onyx'
    static_configs:
      - targets: ['192.168.0.2:9100']
  - job_name: 'ruby'
    static_configs:
      - targets: ['192.168.0.3:9100']
  - job_name: 'home'
    static_configs:
      - targets: ['192.168.0.4:9100']
  - job_name: 'pve'
    static_configs:
      - targets: ['192.168.0.150:9221']
    metrics_path: /pve
    params:
      module: ['default']
# - job_name: 'cadvisor'
#   static_configs:
#     - targets: ['cadvisor:8080']